version: '3.8'

services:
  workflow-approval-service:
    build:
      context: ../
      dockerfile: services/workflow-approval-service/Dockerfile
    container_name: workflow-approval-service
    env_file:
      - ../services/workflow-approval-service/.env.dev
    depends_on:
      - postgres
      - kafka
    ports:
      - "3012:3012"
    networks:
      - app-network
  
  user-service:
    build:
      context: ../
      dockerfile: services/user-service/Dockerfile
    container_name: user-service
    env_file:
      - ../services/user-service/.env.dev
    depends_on:
      - postgres
      - kafka
    ports:
      - "3011:3011"
    networks:
      - app-network

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: workflow-approval
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
