-- init.sql
CREATE DATABASE "analytics-reporting-service";
-- CREATE DATABASE "audit-logging-service";
CREATE DATABASE "billing-service";
CREATE DATABASE "collection-management-service";
-- CREATE DATABASE "consumer-document-management-service";
CREATE DATABASE "consumer-service";
CREATE DATABASE "customer-support-service";
CREATE DATABASE "gis-location-management-service";
CREATE DATABASE "meter-management-inventory-service";
CREATE DATABASE "notification-communication-service";
CREATE DATABASE "policy-management-service";
CREATE DATABASE "third-party-integration-gateway-service";
CREATE DATABASE "user-identity-access-management-service";
CREATE DATABASE "user-service";
CREATE DATABASE "workflow-approval-service";
-- CREATE DATABASE "policy-rule-engine-service";
-- CREATE DATABASE "policy-service";
-- CREATE DATABASE "revenure-forecasting-leakage-detection-service";
-- CREATE DATABASE "scheme-subsidy-management-service";
-- REATE DATABASE "service-request-management-service";
-- CREATE DATABASE "tariff-management-service";
-- CREATE DATABASE "payment-gateway-integration-service";
-- CREATE DATABASE "meter-reading-management-service";
-- CREATE DATABASE "iot-device-management-service";
-- CREATE DATABASE "dynamic-configuration-management-service";
-- CREATE DATABASE "consumer-lifecycle-service";
-- CREATE DATABASE "complaint-grievance-management-service";
-- CREATE DATABASE "billing-lifecycle-management-service";