-- init.sql
CREATE DATABASE "analytics-reporting";
CREATE DATABASE "Billing";
CREATE DATABASE "collection-management";
CREATE DATABASE "Consumers";
CREATE DATABASE "complaint-grievance-management";
CREATE DATABASE "gis-location-management";
CREATE DATABASE "meter-management-inventory";
CREATE DATABASE "notification-communication";
CREATE DATABASE "policy-management";
CREATE DATABASE "third-party-integration-gateway";
CREATE DATABASE "user-identity-access-management";
CREATE DATABASE "Users";
CREATE DATABASE "workflow-approval";
-- CREATE DATABASE "audit-logging-service";
-- CREATE DATABASE "consumer-document-management-service";
-- CREATE DATABASE "policy-rule-engine-service";
-- CREATE DATABASE "policy-service";
-- CREATE DATABASE "revenure-forecasting-leakage-detection-service";
-- CREATE DATABASE "scheme-subsidy-management-service";
-- REATE DATABASE "service-request-management-service";
-- CREATE DATABASE "tariff-management-service";
-- CREATE DATABASE "payment-gateway-integration-service";
-- CREATE DATABASE "meter-reading-management-service";
-- CREATE DATABASE "iot-device-management-service";
-- CREATE DATABASE "dynamic-configuration-management-service";
-- CREATE DATABASE "consumer-lifecycle-service";
-- CREATE DATABASE "complaint-grievance-management-service";
-- CREATE DATABASE "billing-lifecycle-management-service";